CREATE TABLE fact_deliveries (
    shipment_id         VARCHAR(15)  NOT NULL PRIMARY KEY,
    dispatch_date       DATE,
    city                VARCHAR(30),
    postcode_pc4        SMALLINT,
    warehouse_id        VARCHAR(12),
    carrier             VARCHAR(25),
    vehicle_type        VARCHAR(20),
    product_category    VARCHAR(30),
    order_value_eur     DECIMAL(10,2),
    weight_kg           DECIMAL(7,2),
    attempt_1_status    VARCHAR(10),
    attempt_2_status    VARCHAR(10),
    fail_reason         VARCHAR(30),
    final_status        VARCHAR(30),
    delivery_cost_eur   DECIMAL(8,2),
    route_km            DECIMAL(7,2),
    co2_emission_kg     DECIMAL(8,4),
    temp_celsius        DECIMAL(5,1),
    rain_mm             DECIMAL(6,1),
    wind_speed_kmh      DECIMAL(5,1),
    is_peak_period      VARCHAR(3),
    day_of_week         VARCHAR(10),
    month_name          VARCHAR(10),
    year_num            INT,
    week_number         INT,
    yr_month          VARCHAR(7)
);
DESCRIBE fact_deliveries;
